### ISSUE TITLE
Deprecation warning over invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [chrissimpkins/shellescape#3]
Escaping the relevant part or using raw string would fix this.

```
./setup.py:12: DeprecationWarning: invalid escape sequence \s
  major_regex = """major_version\s*?=\s*?["']{1}(\d+)["']{1}"""
./setup.py:13: DeprecationWarning: invalid escape sequence \s
  minor_regex = """minor_version\s*?=\s*?["']{1}(\d+)["']{1}"""
./setup.py:14: DeprecationWarning: invalid escape sequence \s
  patch_regex = """patch_version\s*?=\s*?["']{1}(\d+)["']{1}"""
```

**Comment by chrissimpkins** [comment]
Are you willing to submit a PR to fix it?

**Comment by chrissimpkins** [comment]
Apologize this is the setup.py.  I will take care of this.  Ty for letting me know!

**Comment by tirkarthi** [comment]
No problem :+1:

**Comment by chrissimpkins** [comment]
I updated the `quote` function to the cPython 3.8 definition and will push this fix and the function update out as a new release.  Thanks again!

**Comment by tirkarthi** [comment]
Thanks :)

**Comment by chrissimpkins** [comment]
It is now available on PyPI https://pypi.org/project/shellescape/
