### ISSUE TITLE
Commercial Usage

### ISSUE THREAD

**Issue by hi2rashid** [chrissimpkins/shellescape#5]
We are using this module in our application with Django.

Can you please confirm if its okay to be used commercially.

Thank you in advance

**Comment by chrissimpkins** [comment]
Great!

The usual caveats apply. I am not a lawyer and cannot provide your company with any legal advice on software licensing.  The license is available here https://github.com/chrissimpkins/shellescape/blob/master/docs/LICENSE and you should have a lawyer review it to definitively address your question.

Having said that, I have not included any IP licensing on my end to prevent use in commercial applications.

If your company is interested in supporting my work, you can find my Sponsors page here => https://github.com/sponsors/chrissimpkins and my account on Liberapay here => https://liberapay.com/chrissimpkins/donate

Good luck with your application!
